name: GITAPP actions
on: workflow_dispatch
env:
  AWS_REGION: ap-southeast-1
  ECR_REPOSITORY: git_profile_app
  EKS_CLUSTER: gitops-app

jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Maven Test
        uses: mvn test

      - name: Checkstyle
        run: mvn checkstyle:checkstyle

# Setup Java 11 to be default (sonar-scanner requirement of 5.x)
      - name: Set JAVA 11
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "11"

# Setup sonar-scanner
      - name: SonarQube sSetup
        uses: warchant/setup-sonar-scanner@v7

#Run sonar-scanner
      - name: SonarQube Scanner
        run: sonar-scanner
          -Dsonar.host.url=${{ secrets.SONAR_URL }}
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
          -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
          -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
          -Dsonar.sources=src/
          -Dsonar.junit.reportsPath=target/surefire-reports/
          -Dsonar.jacoco.reportsPath=target/jacoco.exec
          -Dsonar.java.checkstyle.reportsPaths=target/checkstyle-result.xml
          -Dsonar.java.binaries=target/test-classes/com/visualpathit/account

#Check Quality Gate Status
      - name: Quality Gate Status
        id: sonarqube-quality-gate-check
        uses: sonarsource/sonarqube-quality-gate-action@master
        #Force to fail after specific time
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_URL}}